default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: masashi
  password: 0316_My_Password
  host: localhost

development:
  <<: *default
  database: MyCurryApp_development

test:
  <<: *default
  database: MyCurryApp_test

production:
  adapter: postgresql
  database: MyCurryApp_production
  url: <%= ENV['DATABASE_URL'] %>